name: Publish to npm

on:
  push:
    branches: [main]

permissions:
  contents: write   # required to push tags

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Authenticate to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Build if TS
        run: |
          if [ -f tsconfig.json ]; then npm run build; fi

      - name: Get last git tag
        id: get_tag
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "")
          echo "last_tag=$LAST_TAG" >> $GITHUB_OUTPUT

      - name: Get current version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if release needed
        id: should_publish
        run: |
          if [ "${{ steps.get_tag.outputs.last_tag }}" != "v${{ steps.get_version.outputs.version }}" ]; then
            echo "publish=true" >> $GITHUB_OUTPUT
          else
            echo "publish=false" >> $GITHUB_OUTPUT

      - name: Publish to npm
        if: steps.should_publish.outputs.publish == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Tag release
        if: steps.should_publish.outputs.publish == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          VERSION=${{ steps.get_version.outputs.version }}
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"
